---
kind: DeploymentConfig
apiVersion: v1
metadata:
  name: forever-github-runner
spec:
  replicas: 1
  selector:
    name: forever-github-runner
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: forever-github-runner
    spec:
      containers:
        - name: forever-github-runner
          image: docker-registry.default.svc:5000/virt-qe-3rd/github-runner:latest
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "250Mi"
              cpu: "100m"
            limits:
              memory: "500Mi"
              cpu: "500m"
          securityContext:
            capabilities: {}
            privileged: false
          terminationMessagePath: /dev/termination-log
          env:
            - name: RUNNER_ORGANIZATION_URL
              value: https://github.com/virt-s1
            - name: RUNNER_LABELS
              value: DO_NOT_REMOVE
            - name: GITHUB_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: github-access-token
                  key: token
