---
apiVersion: v1
kind: Template
labels:
  template: github-runner-builder
metadata:
  name: github-runner
  annotations:
    tags: github,action,runner

objects:
  - apiVersion: v1
    kind: ImageStream
    metadata:
      labels:
        app: github-runner
      name: github-runner
  - apiVersion: v1
    kind: BuildConfig
    metadata:
      labels:
        app: github-runner
      name: github-runner
    spec:
      output:
        to:
          kind: ImageStreamTag
          name: github-runner:latest
      resources: {}
      source:
        contextDir: ${CONTEXTDIR}
        git:
          ref: ${REPO_REF}
          uri: ${REPO_URL}
        type: Git
      strategy:
        type: Docker
        dockerStrategy:
          forcePull: true
          noCache: true
          env:
            - name: GITHUB_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: github-access-token
                  key: token
      triggers:
        - type: ConfigChange
      successfulBuildsHistoryLimit: 2
      failedBuildsHistoryLimit: 2

parameters:
  - description: Git repository with Dockerfile and entrypoint.
    displayName: Repository URL
    name: REPO_URL
    value: https://github.com/virt-s1/kite-action.git
  - description: The sub-directory inside the repository.
    displayName: Context Directory
    name: CONTEXTDIR
    value: runner
  - description: The git ref or tag to use for customization.
    displayName: Git Reference
    name: REPO_REF
    value: master
