---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: kite-dummy
spec:
  schedule: "0 23 */29 * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            parent: "cronjobdummy"
        spec:
          containers:
            - name: kite-dummy
              image: docker-registry.default.svc:5000/virt-qe-3rd/kite-dummy:latest
              imagePullPolicy: IfNotPresent
              resources:
                limits:
                  cpu: 500m
                  memory: 500Mi
                requests:
                  cpu: 500m
                  memory: 250Mi
              env:
                - name: GITHUB_ACCESS_TOKEN
                  valueFrom:
                    secretKeyRef:
                      key: token
                      name: github-access-token
          restartPolicy: Never
