---
apiVersion: v1
kind: Pod
metadata:
  name: kite-dummy
spec:
  containers:
  - env:
    - name: GITHUB_ACCESS_TOKEN
      valueFrom:
        secretKeyRef:
          key: token
          name: github-access-token
    image: docker-registry.default.svc:5000/virt-qe-3rd/kite-dummy:latest
    imagePullPolicy: IfNotPresent
    name: kite-dummy
    resources:
      limits:
        cpu: 500m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 250Mi
  restartPolicy: Never
